name: API PR Check
on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: api

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'
        cache: true
    - name: Install dependencies
      run: go mod download
    - name: Tidy dependencies
      run: go mod tidy
    - name: Verify dependencies
      run: go mod verify
    - name: Test
      run: |
          set -o pipefail
          go test -v -failfast -coverprofile=coverage.out ./... | grep -v 'no test files'
    - name: Show coverage
      run: go tool cover -func=coverage.out
    - name: Build
      run: go build -v ./cmd/api/main.go